### Реєстрація нового користувача
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "chef_olena1",
  "email": "olen1a@example.com",
  "password": "securepass123",
  "name": "Олена Кравец"
}

### Логін
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "chef_olena",
  "password": "securepass123"
}

### Оновлення токенів
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "refreshToken": "вставте refresh token з відповіді логіну"
}

### Вихід
POST http://localhost:3000/api/auth/logout
Content-Type: application/json

{
  "refreshToken": "вставте refresh token з відповіді логіну"
}

### Отримання інформації про поточного користувача
GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzg1MTczNDA0LCJleHAiOjE3ODUxNzQzMDR9.BtM5_X6oqklP-a_G3n0MUPXcbdJinuBfSWBIhdZGR60


